[project]
name = "web-shop-1"
version = "0.1.0"
description = ""
authors = [
    {name = "GerdCaezar",email = "gerdacaezar@gmail.com"}
]
requires-python = "^3.14"
dependencies = [
    "pytest (>=9.1.1,<10.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 120
exclude = ".git, __pycache__, venv, .venv"
ignore = ["E203", "W503"]

[tool.black]
line-length = 120
target-version = ['py314']

[tool.mypy]
exclude = [
    "^tests/",
    "^venv/",
    "^edu/"
]

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "flake8-pyproject (>=1.2.4,<2.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "isort (>=9.0.1,<10.0.0)"
]
